import React, { useEffect, useState } from 'react';

export default function HomeView(){
  const [backend,setBackend]=useState<any>({status:'starting'}); const [assets,setAssets]=useState<any>({state:'checking_assets'}); const [messages,setMessages]=useState<any[]>([]); const [text,setText]=useState('');
  const [debug,setDebug]=useState(false); const [advanced,setAdvanced]=useState(false); const [details,setDetails]=useState(false); const [diag,setDiag]=useState<any>({entries:[]}); const [sending,setSending]=useState(false);
  useEffect(()=>{ window.villani.getModelBackendStatus?.().then?.(setBackend); window.villani.localAssetsGetStatus?.().then?.(setAssets); window.villani.localAssetsGetDiagnostics?.().then?.(setDiag); window.villani.getChatHistory?.().then?.(setMessages); const off1=window.villani.onBackendStatusUpdated?.(setBackend); const off2=window.villani.onChatUpdated?.(setMessages); const off3=window.villani.onLocalAssetsUpdated?.((s:any)=>{setAssets(s); window.villani.localAssetsGetDiagnostics?.().then?.(setDiag);}); return ()=>{ off1?.(); off2?.(); off3?.(); }; },[]);
  const ready=['running','attached'].includes(backend?.status)&&assets?.state==='ready'; const failed=assets?.state==='failed'; const stepMap:Record<string,string>={checking_assets:'Checking local files...',downloading_llama_server:'Downloading llama-server...',extracting_llama_server:'Extracting llama-server...',downloading_model:'Downloading Qwen model...',verifying_assets:'Verifying local files...',starting_backend:'Starting local model...',ready:'Ready',failed:'Setup failed'};
  const submit=async(e:any)=>{e.preventDefault(); const t=text.trim(); if(!t||!ready||sending) return; setText(''); setSending(true); try{ const out=await window.villani.sendMessage(t); if(Array.isArray(out)) setMessages(out);} finally{setSending(false);} };
  return <div className='vm-shell'><header className='vm-top'><div>Villani Mini</div><span className={`chip ${ready?'ready':failed?'failed':'starting'}`}>{ready?'Ready':'Setting up local model...'}</span><button onClick={()=>setDebug(true)}>⚙</button></header>
    <main className='vm-chat'>{ready&&messages.length===0&&<div className='empty'>Villani Mini is ready.</div>}{messages.map((m:any)=><div key={m.id} className={`row ${m.type}`}><div>{m.text}</div></div>)}</main>
    {!ready&&<div className='card'><div>{failed?'Setup failed':'Setting up local model...'}</div><div>{failed?(assets?.lastError||'Unknown setup error'):stepMap[assets?.state]??'Starting local model...'}</div>{assets?.progress?.total?<div>{Math.round((assets.progress.downloaded/assets.progress.total)*100)}%</div>:null}{failed&&<><button onClick={()=>window.villani.localAssetsRetry?.()}>Retry</button><button onClick={()=>setDetails(v=>!v)}>View details</button><button onClick={()=>setAdvanced(v=>!v)}>Advanced manual setup</button>{details&&<details open><summary>Recent bootstrap logs</summary><pre>{(diag?.entries||[]).slice(-20).map((e:any)=>`${e.timestamp} ${e.level} ${e.step} ${e.message}`).join('\n')}</pre></details>}{advanced&&<div><button onClick={()=>window.villani.localAssetsSelectModel?.()}>Select model</button><button onClick={()=>window.villani.localAssetsSelectServer?.()}>Select llama-server</button></div>}</>}</div>}
    <footer className='vm-input'><form onSubmit={submit} style={{display:'flex',width:'100%',gap:8}}><input disabled={!ready||sending} value={text} onChange={e=>setText(e.target.value)} placeholder={ready?'Message Villani Mini':'Setting up local model...'} /><button type='submit' disabled={!ready||sending||!text.trim()}>Send</button></form></footer>
    {debug&&<aside className='debug'><button onClick={()=>setDebug(false)}>Close</button><div>Status</div><pre>{JSON.stringify({backendStatus:backend?.status,assetState:assets?.state,lastError:assets?.lastError},null,2)}</pre><details><summary>Raw JSON</summary><pre>{JSON.stringify({backend,assets},null,2)}</pre></details><details><summary>Full bootstrap logs</summary><pre>{JSON.stringify(diag?.entries||[],null,2)}</pre></details></aside>}
  </div>;
}
