export type TaskStatus = 'idle'|'running'|'waiting_for_approval'|'waiting_for_user'|'completed'|'blocked'|'error'|'stopped';
export type SetupStatus = 'not_started'|'checking'|'downloading'|'verifying'|'starting'|'ready'|'error';
export type Risk='low'|'medium'|'high';
export type ActionStatus = 'proposed'|'approved'|'rejected'|'executing'|'completed'|'failed';
export interface ClickableCandidate { id:string; role:string; label:string; text:string; href?:string; ariaLabel?:string; title?:string; placeholder?:string; name?:string; elementId?:string; type?:string; disabled?:boolean; enabled?:boolean; visible?:boolean; framePath?:string; boundingBox?:{x:number;y:number;width:number;height:number}; fingerprint?:string; selectorHint?:string; buttonType?:string; riskHints:string[]; isSubmitLike:boolean; isDangerous:boolean; reasonFlags:string[] }
export interface FormFieldCandidate { id:string; label:string; type:string; sensitive:boolean; required?:boolean; name?:string; placeholder?:string; ariaLabel?:string; elementId?:string; disabled?:boolean; enabled?:boolean; visible?:boolean; framePath?:string; boundingBox?:{x:number;y:number;width:number;height:number}; fingerprint?:string; selectorHint?:string; valuePreview?:string; }
export interface BrowserSnapshot { snapshotId:string; url:string; title:string; status:'ok'|'error'; timestamp?:string; capturedAt?:string; visibleTextSummary?:string; textExcerpt?:string; candidates?:ClickableCandidate[]; clickableCandidates?:ClickableCandidate[]; fields?:FormFieldCandidate[]; formFields?:FormFieldCandidate[]; error?:string; }
export interface CompactTaskState { goal:string; currentObjective:string; factsLearned:string[]; decisionsMade:string[]; evidenceRefs:string[]; openQuestions:string[]; userProvidedAnswers:string[]; knownPageEntities:string[]; formsDiscovered:string[]; completedSteps:string[]; failedAttempts:string[]; blockedReasons:string[]; lastActionSummary:string; nextRecommendedStep:string; progressFingerprint:string; lastUpdatedAt:string; }
export interface ActionRecord { id:string; taskId:string; type:string; params:Record<string,unknown>; title:string; reason:string; expectedOutcome:string; riskLevel:Risk; requiresApproval:boolean; reversible:boolean; evidenceRefs:string[]; createdAt:string; updatedAt:string; status:ActionStatus; observationSummary?:string; error?:string; rejectionReason?:string; approvalDetails?:ApprovalDetails; }
export interface ApprovalDetails { targetSummary:string; riskReasons:string[]; snapshotId?:string; candidateId?:string; fieldId?:string; }
export interface RunnerEvent { id:string; taskId:string; type:string; summary:string; at:string; refId?:string; }
