import { contextBridge, ipcRenderer } from 'electron';
type Unsubscribe=()=>void;
type VillaniApi=any;
const villani:VillaniApi={
chat:{sendMessage:(text:string)=>ipcRenderer.invoke('chat:sendMessage',text),getMessages:()=>ipcRenderer.invoke('chat:getHistory'),approve:(taskId:string,proposalId:string)=>ipcRenderer.invoke('chat:approve',taskId,proposalId),reject:(taskId:string,proposalId:string,reason?:string)=>ipcRenderer.invoke('chat:reject',taskId,proposalId,reason),answer:(taskId:string,answer:string)=>ipcRenderer.invoke('chat:answer',taskId,answer),onUpdated:(cb:(messages:any[])=>void)=>{const l=(_e:unknown,p:any[])=>cb(p);ipcRenderer.on('chat:updated',l);return ()=>ipcRenderer.removeListener('chat:updated',l);}},
task:{list:()=>ipcRenderer.invoke('task:list'),getState:(taskId:string)=>ipcRenderer.invoke('task:getState',taskId),run:(taskId:string,options?:unknown)=>ipcRenderer.invoke('task:run',taskId,options),step:(taskId:string)=>ipcRenderer.invoke('task:step',taskId),stop:(taskId:string)=>ipcRenderer.invoke('task:stop',taskId),answerUserQuestion:(taskId:string,answer:string)=>ipcRenderer.invoke('chat:answer',taskId,answer),approveAction:(taskId:string,proposalId:string)=>ipcRenderer.invoke('chat:approve',taskId,proposalId),rejectAction:(taskId:string,proposalId:string,reason?:string)=>ipcRenderer.invoke('chat:reject',taskId,proposalId,reason),openDebugFolder:(taskId:string)=>ipcRenderer.invoke('task:openDebugFolder',taskId),copyDebugSummary:(taskId:string)=>ipcRenderer.invoke('task:copyDebugSummary',taskId),onEvent:(cb:(event:any)=>void)=>{const l=(_e:unknown,p:any)=>cb(p);ipcRenderer.on('task:event',l);return ()=>ipcRenderer.removeListener('task:event',l);}},
backend:{getStatus:()=>ipcRenderer.invoke('modelBackend:getStatus'),retry:()=>ipcRenderer.invoke('modelBackend:restart'),retryStart:()=>ipcRenderer.invoke('setup:retryBackend'),stop:()=>ipcRenderer.invoke('modelBackend:stop'),onUpdated:(cb:(s:any)=>void)=>{const l=(_e:unknown,p:any)=>cb(p);ipcRenderer.on('modelBackend:statusUpdated',l);return ()=>ipcRenderer.removeListener('modelBackend:statusUpdated',l);}},
browser:{getStatus:()=>ipcRenderer.invoke('browser:getStatus'),getViewportStatus:()=>ipcRenderer.invoke('browser:getViewportStatus'),attachToViewport:(bounds:any)=>ipcRenderer.invoke('browser:attachToViewport',bounds),show:()=>ipcRenderer.invoke('browser:show'),hide:()=>ipcRenderer.invoke('browser:hide'),openUrl:(url:string)=>ipcRenderer.invoke('browser:openUrl',url),readCurrentPage:()=>ipcRenderer.invoke('browser:readCurrentPage'),installDependencies:()=>ipcRenderer.invoke('browser:installDependencies')},
browserMission:{start:(input:any)=>ipcRenderer.invoke('browserMission:start',input),pause:(id:string)=>ipcRenderer.invoke('browserMission:pause',id),resume:(id:string)=>ipcRenderer.invoke('browserMission:resume',id),stop:(id:string)=>ipcRenderer.invoke('browserMission:stop',id),getState:(id:string)=>ipcRenderer.invoke('browserMission:getState',id),getEvents:(id:string)=>ipcRenderer.invoke('browserMission:getEvents',id),getTranscript:(id:string)=>ipcRenderer.invoke('browserMission:getTranscript',id),approve:(id:string,a:string)=>ipcRenderer.invoke('browserMission:approve',id,a),reject:(id:string,a:string)=>ipcRenderer.invoke('browserMission:reject',id,a)},
events:{onBrowserMissionEvent:(cb:(e:any)=>void):Unsubscribe=>{const l=(_e:unknown,p:any)=>cb(p);ipcRenderer.on('browserMission:event',l);return ()=>ipcRenderer.removeListener('browserMission:event',l);}},
config:{getBackendConfig:()=>ipcRenderer.invoke('modelBackend:getConfig'),updateBackendConfig:(patch:any)=>ipcRenderer.invoke('modelBackend:updateConfig',patch)},
assets:{getStatus:()=>ipcRenderer.invoke('localAssets:getStatus'),retry:()=>ipcRenderer.invoke('localAssets:retry'),retryOnly:()=>ipcRenderer.invoke('setup:retryAssets'),onUpdated:(cb:(s:any)=>void)=>{const l=(_e:unknown,p:any)=>cb(p);ipcRenderer.on('localAssets:statusUpdated',l);return ()=>ipcRenderer.removeListener('localAssets:statusUpdated',l);}},
setup:{retryAssets:()=>ipcRenderer.invoke('setup:retryAssets'),retryBackend:()=>ipcRenderer.invoke('setup:retryBackend'),retryAll:()=>ipcRenderer.invoke('setup:retryAll'),getStatus:()=>ipcRenderer.invoke('setup:getStatus')},localAssetsSelectModel:()=>ipcRenderer.invoke('localAssets:selectModelFile'),localAssetsSelectServer:()=>ipcRenderer.invoke('localAssets:selectServerBinary')};
contextBridge.exposeInMainWorld('villani',villani);
